name: Publish CSV [beta] to release

on:
  push:
    branches:
      - data

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            files/hebdo/beta.csv
            files/hebdo/timestamp.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
